ImageGallery.UI/Models/ErrorViewModel.cs
using System;

namespace ImageGallery.UI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ImageGallery.UI/Models/GalleryDetailModel.cs
using System;
using System.Collections.Generic;

namespace ImageGallery.UI.Models
{
    public class GalleryDetailModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime CreatedOn { get; set; }
        public string Url { get; set; }

        public List<string> Tags { get; set; }
    }
}

ImageGallery.UI/Models/GalleryIndexModel.cs
using ImageGallery.Data.Models;
using System.Collections.Generic;

namespace ImageGallery.UI.Models
{
    public class GalleryIndexModel
    {
        public IEnumerable<GalleryImage> Images { get; set; }
        public string SearchQuery { get; set; }
    }
}

ImageGallery.UI/Models/UploadImageModel.cs
using Microsoft.AspNetCore.Http;

namespace ImageGallery.UI.Models
{
    public class UploadImageModel
    {
        public string Title { get; set; }
        public string Tags { get; set; }
        public IFormFile ImageUpload { get; set; }
    }
}

ImageGallery.UI/Controllers/GalleryController.cs
using ImageGallery.Data;
using ImageGallery.UI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace ImageGallery.UI.Controllers
{
    public class GalleryController : Controller
    {
        private readonly IImage _imageService;

        public GalleryController(IImage imageService)
        {
            _imageService = imageService;
        }

        public IActionResult Index()
        {
            var imagesList = _imageService.GetAll();

            var model = new GalleryIndexModel()
            {
                Images = imagesList,
                SearchQuery = ""
            };
            return View(model);
        }

        public IActionResult Detail(int id)
        {
            var image = _imageService.GetById(id);

            var model = new GalleryDetailModel()
            {
                Id = image.Id,
                Title = image.Title,
                CreatedOn = image.Created,
                Url = image.Url,
                Tags = image.Tags.Select(t => t.Description).ToList()
            };

            return View(model);
        }
    }
}

ImageGallery.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ImageGallery.UI.Models;

namespace ImageGallery.UI.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ImageGallery.UI/Controllers/ImageController.cs
using ImageGallery.UI.Models;
using Microsoft.AspNetCore.Mvc;
using ImageGallery.Service;
using Microsoft.Extensions.Configuration;

namespace ImageGallery.UI.Controllers
{
    public class ImageController : Controller
    {
        private IConfiguration _configuration;
        private ImageService _imageService;
        private string DefaultConnectionString { get; }

        public ImageController(IConfiguration configuration, ImageService imageService)
        {
            _configuration = configuration;
            _imageService = imageService;
            DefaultConnectionString = _configuration["DefaultConnectionString"];
        }

        public IActionResult Upload()
        {
            var model = new UploadImageModel();
            return View(model);
        }

        [HttpPost]
        public IActionResult UploadNewImage()
        {
            return Ok();
        }
    }
}

ImageGallery.UI/Views/Gallery/Detail.cshtml
@model ImageGallery.UI.Models.GalleryDetailModel

<div class="container body-content">
    <div class="row image-detail-container">
        <div class="image-detail">
            <img src="@Model.Url" alt="@Model.Title"/>
        </div>
    </div>
    <div class="row image-detail-meta">
        <span>Title: @Model.Title</span>
        <span>Uploaded: @Model.CreatedOn</span>
    </div>
    <div class="row controls">
        <a class="btn btn-primary" asp-controller="Gallery" asp-action="Index">
            Back to Gallery
        </a>
    </div>
</div>

ImageGallery.UI/Views/Gallery/Index.cshtml
@model ImageGallery.UI.Models.GalleryIndexModel

<div class="container body-content">
    <div class="row gallery-content">
        @foreach (var image in Model.Images)
        {
            <div class="gallery-image-container drop-shadow">
                <a asp-controller="Gallery" asp-action="Detail" asp-route-id="@image.Id">
                    <div class="gallery-image" style="background-image: url(@image.Url)"></div>
                </a>
            </div>
        }
    </div>
</div>

ImageGallery.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ImageGallery.UI/Views/Image/Upload.cshtml
@model ImageGallery.UI.Models.UploadImageModel

<div class="container body-content">
    <div class="row upload-container">
        <div class="upload-from drop-shadow">
            <form asp-action="UploadNewImage" method="post" enctype="multipart/form-data" id="upload-form">
                <div class="form-group">
                    <label asp-for="Title"></label>
                    <input type="text" asp-for="Title" placeholder="Title" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Tags"></label>
                    <input type="text" asp-for="Tags" placeholder="Tags" class="form-control" />
                </div>
                <div>
                    <label class="btn btn-outline-warning">
                        Browse for Image
                        <input type="file" name="file" style="display: none" />
                    </label>
                </div>
                <div>
                    <button type="submit" id="btn-upload" class="btn btn-info">
                        Submit
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

ImageGallery.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ImageGallery.UI</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Gallery" asp-action="Index">ImageGallery.UI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Gallery" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Image" asp-action="Upload">Upload</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Gallery" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - ImageGallery.UI - <a asp-area="" asp-controller="Gallery" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>